"""S-127 权威表 —— 由 gen_s127_catalogue.py 从官方要素目录 S127FC.xml 生成。

**不要手工编辑。** 要素目录换版就重跑：python scripts/gen_s127_catalogue.py

来源：S127FC.xml（S-100 Part 5 Feature Catalogue for S-127）
版本：1.0.1-20190628（2019-06-28）
规模：23 个地理要素类、12 个信息要素类、8 个抽象类、
      143 个属性、50 个枚举属性 / 431 个枚举值、
      22 个复合属性、33 个关联角色、
      19 个关联类。

枚举 code 是要素目录里的官方数值（listedValue/code），不是推导值。
注意官方 code **不连续**：如 status 是 1~9、12、14~18、28；
restriction 到 39 但缺 38；categoryOfMilitaryPracticeArea 从 2 起。
"""

FC_VERSION = '1.0.1-20190628'
FC_DATE = '2019-06-28'

# 抽象类（不可实例化，只贡献继承属性）
ABSTRACT_TYPES = [
    'AbstractRxN',
    'DataQuality',
    'FeatureType',
    'InformationType',
    'OrganisationContactArea',
    'QualityOfTemporalVariation',
    'ReportableServiceArea',
    'SupervisedArea',
]

# 要素类 → 种类 / 继承链 / 允许几何图元 / 定义
FEATURES = {
    'CautionArea': {
        'name': 'Caution area',
        'kind': 'geographic',
        'superType': 'FeatureType',
        'chain': ['FeatureType', 'CautionArea'],
        'primitives': ['point', 'surface'],
        'definition': 'Generally, an area where the mariner has to be made aware of circumstances influencing the safety of navigation.',
    },
    'ConcentrationOfShippingHazardArea': {
        'name': 'Concentration of shipping hazard area',
        'kind': 'geographic',
        'superType': 'FeatureType',
        'chain': ['FeatureType', 'ConcentrationOfShippingHazardArea'],
        'primitives': ['surface'],
        'definition': 'An area where hazards, caused by concentrations of shipping, may occur. Hazards are risks to shipping, which stem from sources other than shoal water or obstructions.',
    },
    'IspsCodeSecurityLevel': {
        'name': 'ISPS code security level',
        'kind': 'geographic',
        'superType': 'OrganisationContactArea',
        'chain': ['FeatureType', 'OrganisationContactArea', 'IspsCodeSecurityLevel'],
        'primitives': ['curve', 'surface'],
        'definition': 'The area to which an International Ship and Port Facility Security (ISPS) level applies.',
    },
    'LocalPortServiceArea': {
        'name': 'Local Port Service Area',
        'kind': 'geographic',
        'superType': 'ReportableServiceArea',
        'chain': [
            'FeatureType',
            'OrganisationContactArea',
            'SupervisedArea',
            'ReportableServiceArea',
            'LocalPortServiceArea',
        ],
        'primitives': ['surface'],
        'definition': 'A service established to provide port information without interaction between the customer and the service provider. This information could be inter alia berthing information, availability of port services, shipping schedules, meteorological and hydrological data.',
    },
    'MilitaryPracticeArea': {
        'name': 'Military practice area',
        'kind': 'geographic',
        'superType': 'SupervisedArea',
        'chain': ['FeatureType', 'OrganisationContactArea', 'SupervisedArea', 'MilitaryPracticeArea'],
        'primitives': ['point', 'surface'],
        'definition': "An area within which naval, military or aerial exercises are carried out. Also called an 'exercise area'.",
    },
    'PilotBoardingPlace': {
        'name': 'Pilot boarding place',
        'kind': 'geographic',
        'superType': 'OrganisationContactArea',
        'chain': ['FeatureType', 'OrganisationContactArea', 'PilotBoardingPlace'],
        'primitives': ['point', 'surface'],
        'definition': 'The meeting place to which the pilot comes out.',
    },
    'PilotService': {
        'name': 'Pilot service',
        'kind': 'geographic',
        'superType': 'ReportableServiceArea',
        'chain': ['FeatureType', 'OrganisationContactArea', 'SupervisedArea', 'ReportableServiceArea', 'PilotService'],
        'primitives': ['surface'],
        'definition': 'The service provided by a person who directs the movements of a vessel through pilot waters, usually a person who has demonstrated extensive knowledge of channels, aids to navigation, dangers to navigation, etc., in a particular area and is licensed for that area.',
    },
    'PilotageDistrict': {
        'name': 'Pilotage district',
        'kind': 'geographic',
        'superType': 'FeatureType',
        'chain': ['FeatureType', 'PilotageDistrict'],
        'primitives': ['surface'],
        'definition': 'An area within which a pilotage direction exists. Such directions are regulated by a competent harbour authority which dictates circumstances under which they apply.',
    },
    'PiracyRiskArea': {
        'name': 'Piracy risk area',
        'kind': 'geographic',
        'superType': 'ReportableServiceArea',
        'chain': [
            'FeatureType',
            'OrganisationContactArea',
            'SupervisedArea',
            'ReportableServiceArea',
            'PiracyRiskArea',
        ],
        'primitives': ['point', 'surface'],
        'definition': 'An area where there is a raised risk of piracy or armed robbery.',
    },
    'PlaceOfRefuge': {
        'name': 'Place of refuge',
        'kind': 'geographic',
        'superType': 'ReportableServiceArea',
        'chain': [
            'FeatureType',
            'OrganisationContactArea',
            'SupervisedArea',
            'ReportableServiceArea',
            'PlaceOfRefuge',
        ],
        'primitives': ['point', 'surface'],
        'definition': 'A place where a ship in need of assistance can take action to enable it to stabilize its condition and reduce the hazards to navigation, and to protect human life and the environment.',
    },
    'RadarRange': {
        'name': 'Radar range',
        'kind': 'geographic',
        'superType': 'FeatureType',
        'chain': ['FeatureType', 'RadarRange'],
        'primitives': ['surface'],
        'definition': 'Indicates the coverage of a sea area by a radar surveillance station. Inside this area a vessel may request shore-based radar assistance, particularly in poor visibility.',
    },
    'RadioCallingInPoint': {
        'name': 'Radio calling-in point',
        'kind': 'geographic',
        'superType': 'FeatureType',
        'chain': ['FeatureType', 'RadioCallingInPoint'],
        'primitives': ['point', 'curve'],
        'definition': "On passing a radio callin-in point or crossing a defined line vessels are required to report on VHF to a Traffic Control Centre. The attribute 'orientation' (ORIENT) encodes the orientation of the traffic flow at that point.",
    },
    'RestrictedAreaNavigational': {
        'name': 'Restricted area navigational',
        'kind': 'geographic',
        'superType': 'SupervisedArea',
        'chain': ['FeatureType', 'OrganisationContactArea', 'SupervisedArea', 'RestrictedAreaNavigational'],
        'primitives': ['surface'],
        'definition': 'A specified area of land or water designated by an appropriate authority within which access or navigation is restricted in accordance with certain specified conditions.\n\t\t\t\tA navigational restricted area is an area where the restrictions have a direct impact on the navigation of a vessel in the area.',
    },
    'RestrictedAreaRegulatory': {
        'name': 'Restricted area regulatory',
        'kind': 'geographic',
        'superType': 'SupervisedArea',
        'chain': ['FeatureType', 'OrganisationContactArea', 'SupervisedArea', 'RestrictedAreaRegulatory'],
        'primitives': ['surface'],
        'definition': 'A specified area of land or water designated by an appropriate authority within which access or navigation is restricted in accordance with certain specified conditions. A regulatory restricted area is an area where the restrictions have no direct impact on the navigation of a vessel in the area, but impact on the activities that can take place within the area.',
    },
    'RouteingMeasure': {
        'name': 'Routeing measure',
        'kind': 'geographic',
        'superType': 'FeatureType',
        'chain': ['FeatureType', 'RouteingMeasure'],
        'primitives': ['surface', 'curve'],
        'definition': 'An area or line designating the limits or central line of a routeing measure (or part of a routeing measure). Routeing measures include traffic separation schemes, deep-water routes, two-way routes, archipelagic sea lanes, and fairway systems.',
    },
    'ShipReportingServiceArea': {
        'name': 'Ship Reporting Service Area',
        'kind': 'geographic',
        'superType': 'ReportableServiceArea',
        'chain': [
            'FeatureType',
            'OrganisationContactArea',
            'SupervisedArea',
            'ReportableServiceArea',
            'ShipReportingServiceArea',
        ],
        'primitives': ['surface'],
        'definition': 'A service established by a relevant authority consisting of one or more reporting points or lines at which ships are required to report their identity, course, speed and other data to the monitoring authority.',
    },
    'SignalStationWarning': {
        'name': 'Signal Station Warning',
        'kind': 'geographic',
        'superType': 'FeatureType',
        'chain': ['FeatureType', 'SignalStationWarning'],
        'primitives': ['point', 'surface'],
        'definition': 'A warning signal station is a place on shore from which warning signals are made to ships at sea.',
    },
    'SignalStationTraffic': {
        'name': 'Signal Station Traffic',
        'kind': 'geographic',
        'superType': 'OrganisationContactArea',
        'chain': ['FeatureType', 'OrganisationContactArea', 'SignalStationTraffic'],
        'primitives': ['point', 'surface'],
        'definition': 'A traffic signal station is a place on shore from which signals are made to regulate the movement of traffic.',
    },
    'UnderkeelClearanceAllowanceArea': {
        'name': 'Underkeel clearance allowance area',
        'kind': 'geographic',
        'superType': 'FeatureType',
        'chain': ['FeatureType', 'UnderkeelClearanceAllowanceArea'],
        'primitives': ['surface'],
        'definition': 'An area for which an authority has stated underkeel allowance requirements.',
    },
    'UnderkeelClearanceManagementArea': {
        'name': 'Underkeel clearance management area',
        'kind': 'geographic',
        'superType': 'ReportableServiceArea',
        'chain': [
            'FeatureType',
            'OrganisationContactArea',
            'SupervisedArea',
            'ReportableServiceArea',
            'UnderkeelClearanceManagementArea',
        ],
        'primitives': ['surface'],
        'definition': 'An area for which an authority permits use of dynamic underkeel clearance information or provides dynamic information related to underkeel clearances.',
    },
    'VesselTrafficServiceArea': {
        'name': 'Vessel Traffic Service Area',
        'kind': 'geographic',
        'superType': 'ReportableServiceArea',
        'chain': [
            'FeatureType',
            'OrganisationContactArea',
            'SupervisedArea',
            'ReportableServiceArea',
            'VesselTrafficServiceArea',
        ],
        'primitives': ['surface'],
        'definition': 'The area of any service implemented by a relevant authority primarily designed to improve safety and efficiency of traffic flow and the protection of the environment. It may range from simple information messages, to extensive organisation of the traffic involving national or regional schemes.',
    },
    'WaterwayArea': {
        'name': 'Waterway area',
        'kind': 'geographic',
        'superType': 'SupervisedArea',
        'chain': ['FeatureType', 'OrganisationContactArea', 'SupervisedArea', 'WaterwayArea'],
        'primitives': ['surface'],
        'definition': 'An area in which uniform general information of the waterway exists.',
    },
    'DataCoverage': {
        'name': 'Data coverage',
        'kind': 'meta',
        'superType': None,
        'chain': ['DataCoverage'],
        'primitives': ['surface'],
        'definition': 'A geographical area that describes the coverage and extent of spatial objects.',
    },
    'QualityOfNonBathymetricData': {
        'name': 'Quality of Non-Bathymetric Data',
        'kind': 'meta',
        'superType': 'QualityOfTemporalVariation',
        'chain': ['DataQuality', 'QualityOfTemporalVariation', 'QualityOfNonBathymetricData'],
        'primitives': ['surface'],
        'definition': 'An area within which a uniform assessment of the quality of the non-bathymetric data exists',
    },
    'TextPlacement': {
        'name': 'Text Placement',
        'kind': 'geographic',
        'superType': None,
        'chain': ['TextPlacement'],
        'primitives': ['point'],
        'definition': 'The Text Placement feature is used in association with the Feature Name attribute or a light description to optimise text positioning in ECDIS.',
    },
    'Applicability': {
        'name': 'Applicability',
        'kind': 'information',
        'superType': 'InformationType',
        'chain': ['InformationType', 'Applicability'],
        'primitives': [],
        'definition': 'Describes the relationship between vessel characteristics and: (i) the applicability of an associated information object or feature to the vessel; or, (ii) the use of a facility, place, or service by the vessel; or, (iii) passage of the vessel through an area.',
    },
    'Authority': {
        'name': 'Authority',
        'kind': 'information',
        'superType': 'InformationType',
        'chain': ['InformationType', 'Authority'],
        'primitives': [],
        'definition': 'A person or organization that has the legally delegated or invested authority, capacity, or power to perform a designated function or exert administrative control.',
    },
    'ContactDetails': {
        'name': 'Contact details',
        'kind': 'information',
        'superType': 'InformationType',
        'chain': ['InformationType', 'ContactDetails'],
        'primitives': [],
        'definition': 'information on how to reach a person or organisation by postal, internet, telephone, telex and radio systems',
    },
    'NauticalInformation': {
        'name': 'Nautical information',
        'kind': 'information',
        'superType': 'AbstractRxN',
        'chain': ['InformationType', 'AbstractRxN', 'NauticalInformation'],
        'primitives': [],
        'definition': 'Nautical information about a related area or facility.',
    },
    'NonStandardWorkingDay': {
        'name': 'Non-standard working day',
        'kind': 'information',
        'superType': 'InformationType',
        'chain': ['InformationType', 'NonStandardWorkingDay'],
        'primitives': [],
        'definition': 'Days when many services are not available. Often days of festivity or recreation or public holidays when normal working hours are limited, especially a national or religious festival, etc.',
    },
    'ServiceHours': {
        'name': 'Service Hours',
        'kind': 'information',
        'superType': 'InformationType',
        'chain': ['InformationType', 'ServiceHours'],
        'primitives': [],
        'definition': 'The time when a service is available and known exceptions.',
    },
    'ShipReport': {
        'name': 'Ship Report',
        'kind': 'information',
        'superType': 'InformationType',
        'chain': ['InformationType', 'ShipReport'],
        'primitives': [],
        'definition': 'Describes how a ship should report to a maritime authority, including when to report, what to report and whether the format conforms to the IMO standard.',
    },
    'Recommendations': {
        'name': 'Recommendations',
        'kind': 'information',
        'superType': 'AbstractRxN',
        'chain': ['InformationType', 'AbstractRxN', 'Recommendations'],
        'primitives': [],
        'definition': 'Recommendations for a related area or facility.',
    },
    'Regulations': {
        'name': 'Regulations',
        'kind': 'information',
        'superType': 'AbstractRxN',
        'chain': ['InformationType', 'AbstractRxN', 'Regulations'],
        'primitives': [],
        'definition': 'Regulations for a related area or facility.',
    },
    'Restrictions': {
        'name': 'Restrictions',
        'kind': 'information',
        'superType': 'AbstractRxN',
        'chain': ['InformationType', 'AbstractRxN', 'Restrictions'],
        'primitives': [],
        'definition': 'Restrictions for a related area or facility.',
    },
    'SpatialQuality': {
        'name': 'Spatial Quality',
        'kind': 'information',
        'superType': None,
        'chain': ['SpatialQuality'],
        'primitives': [],
        'definition': '',
    },
    'SpatialQualityPoints': {
        'name': 'Spatial Quality Points',
        'kind': 'information',
        'superType': 'SpatialQuality',
        'chain': ['SpatialQuality', 'SpatialQualityPoints'],
        'primitives': [],
        'definition': '',
    },
}

# 要素类 → {属性: (lower, upper, 允许的枚举 code 子集或 None)}；upper=-1 表示不限
BINDINGS = {
    'CautionArea': {
        'fixedDateRange': (0, 1, None),
        'periodicDateRange': (0, -1, None),
        'featureName': (0, -1, None),
        'sourceIndication': (0, 1, None),
        'textContent': (0, 1, None),
        'condition': (0, 1, [1, 3, 5]),
        'status': (0, 1, [5, 7]),
    },
    'ConcentrationOfShippingHazardArea': {
        'fixedDateRange': (0, 1, None),
        'periodicDateRange': (0, -1, None),
        'featureName': (0, -1, None),
        'sourceIndication': (0, 1, None),
        'textContent': (0, 1, None),
        'categoryOfConcentrationOfShippingHazardArea': (0, -1, [1, 2, 3, 4]),
        'status': (0, -1, [1, 2, 5, 7, 16, 17]),
    },
    'IspsCodeSecurityLevel': {
        'fixedDateRange': (0, 1, None),
        'periodicDateRange': (0, -1, None),
        'featureName': (0, -1, None),
        'sourceIndication': (0, 1, None),
        'textContent': (0, 1, None),
        'ispsLevel': (1, 1, [1, 2, 3]),
    },
    'LocalPortServiceArea': {
        'fixedDateRange': (0, 1, None),
        'periodicDateRange': (0, -1, None),
        'featureName': (0, -1, None),
        'sourceIndication': (0, 1, None),
        'textContent': (0, 1, None),
        'serviceAccessProcedure': (0, 1, None),
        'requirementsForMaintenanceOfListeningWatch': (1, 1, None),
    },
    'MilitaryPracticeArea': {
        'fixedDateRange': (0, 1, None),
        'periodicDateRange': (0, -1, None),
        'featureName': (0, -1, None),
        'sourceIndication': (0, 1, None),
        'textContent': (0, 1, None),
        'categoryOfMilitaryPracticeArea': (0, -1, [2, 3, 4, 5, 6]),
        'nationality': (0, 1, None),
        'restriction': (
            0,
            -1,
            [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 39],
        ),
        'status': (0, -1, [1, 2, 5, 6, 7, 16, 17]),
    },
    'PilotBoardingPlace': {
        'fixedDateRange': (0, 1, None),
        'periodicDateRange': (0, -1, None),
        'featureName': (0, -1, None),
        'sourceIndication': (0, 1, None),
        'textContent': (0, 1, None),
        'callSign': (0, 1, None),
        'categoryOfPilotBoardingPlace': (0, 1, [1, 2, 3]),
        'categoryOfPreference': (0, 1, [1, 2]),
        'categoryOfVessel': (0, 1, [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17]),
        'communicationChannel': (0, -1, None),
        'destination': (0, 1, None),
        'pilotMovement': (0, 1, [1, 2, 3]),
        'pilotVessel': (0, 1, None),
        'status': (0, -1, [1, 2, 5, 6, 9, 16, 17, 28]),
    },
    'PilotService': {
        'fixedDateRange': (0, 1, None),
        'periodicDateRange': (0, -1, None),
        'featureName': (0, -1, None),
        'sourceIndication': (0, 1, None),
        'textContent': (0, 1, None),
        'categoryOfPilot': (0, -1, [1, 2, 3, 4, 5, 6, 7]),
        'pilotQualification': (0, 1, [1, 2, 3, 4, 5, 6, 7, 8]),
        'pilotRequest': (0, 1, None),
        'remotePilot': (1, 1, None),
        'noticeTime': (0, 1, None),
    },
    'PilotageDistrict': {
        'fixedDateRange': (0, 1, None),
        'periodicDateRange': (0, -1, None),
        'featureName': (0, -1, None),
        'sourceIndication': (0, 1, None),
        'textContent': (0, 1, None),
        'communicationChannel': (0, -1, None),
    },
    'PiracyRiskArea': {
        'fixedDateRange': (0, 1, None),
        'periodicDateRange': (0, -1, None),
        'featureName': (0, -1, None),
        'sourceIndication': (0, 1, None),
        'textContent': (0, 1, None),
        'restriction': (1, -1, [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 14, 18, 19, 20, 21, 24, 25, 26, 27, 31, 32, 33, 34]),
        'status': (0, -1, [1, 2, 5, 7]),
    },
    'PlaceOfRefuge': {
        'fixedDateRange': (0, 1, None),
        'periodicDateRange': (0, -1, None),
        'featureName': (0, -1, None),
        'sourceIndication': (0, 1, None),
        'textContent': (0, 1, None),
        'communicationChannel': (0, -1, None),
        'status': (0, -1, [1, 2, 3, 4, 5, 6, 7, 8, 9, 28]),
    },
    'RadarRange': {
        'fixedDateRange': (0, 1, None),
        'periodicDateRange': (0, -1, None),
        'featureName': (0, -1, None),
        'sourceIndication': (0, 1, None),
        'textContent': (0, 1, None),
        'communicationChannel': (0, -1, None),
        'status': (0, -1, [1, 2, 4, 7]),
    },
    'RadioCallingInPoint': {
        'fixedDateRange': (0, 1, None),
        'periodicDateRange': (0, -1, None),
        'featureName': (0, -1, None),
        'sourceIndication': (0, 1, None),
        'textContent': (0, 1, None),
        'callSign': (0, 1, None),
        'communicationChannel': (0, -1, None),
        'categoryOfCargo': (0, -1, [1, 2, 3, 4, 5, 6, 7, 8, 9]),
        'categoryOfVessel': (0, -1, [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17]),
        'orientationValue': (0, 2, None),
        'status': (0, -1, [1, 3, 4, 5, 6, 7, 9]),
        'trafficFlow': (1, 1, [1, 2, 3, 4]),
    },
    'RestrictedAreaNavigational': {
        'fixedDateRange': (0, 1, None),
        'periodicDateRange': (0, -1, None),
        'featureName': (0, -1, None),
        'sourceIndication': (0, 1, None),
        'textContent': (0, 1, None),
        'categoryOfRestrictedArea': (0, -1, [1, 4, 5, 6, 7, 8, 9, 10, 12, 14, 19, 20, 22, 23, 25, 27, 28, 29, 30, 31, 32]),
        'restriction': (1, -1, [1, 2, 7, 8, 13, 14, 25, 26, 27, 28, 29, 30, 35, 36, 37]),
        'status': (0, -1, [1, 2, 3, 4, 5, 6, 7, 9, 18, 28]),
    },
    'RestrictedAreaRegulatory': {
        'fixedDateRange': (0, 1, None),
        'periodicDateRange': (0, -1, None),
        'featureName': (0, -1, None),
        'sourceIndication': (0, 1, None),
        'textContent': (0, 1, None),
        'categoryOfRestrictedArea': (0, -1, [1, 4, 5, 6, 7, 8, 9, 10, 12, 14, 19, 20, 22, 23, 25, 27, 28, 29, 30, 31, 32]),
        'restriction': (0, -1, [3, 4, 5, 6, 9, 10, 11, 12, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 39]),
        'status': (0, -1, [1, 2, 3, 4, 5, 6, 7, 9, 18, 28]),
    },
    'RouteingMeasure': {
        'fixedDateRange': (0, 1, None),
        'periodicDateRange': (0, -1, None),
        'featureName': (0, -1, None),
        'sourceIndication': (0, 1, None),
        'textContent': (0, 1, None),
        'categoryOfRouteingMeasure': (1, 1, [1, 2, 3, 4, 5, 6]),
        'categoryOfTrafficSeparationScheme': (0, 1, [1, 2]),
        'categoryOfNavigationLine': (0, 1, [1, 2, 3]),
    },
    'ShipReportingServiceArea': {
        'fixedDateRange': (0, 1, None),
        'periodicDateRange': (0, -1, None),
        'featureName': (0, -1, None),
        'sourceIndication': (0, 1, None),
        'textContent': (0, 1, None),
        'serviceAccessProcedure': (0, 1, None),
        'requirementsForMaintenanceOfListeningWatch': (1, 1, None),
    },
    'SignalStationWarning': {
        'fixedDateRange': (0, 1, None),
        'periodicDateRange': (0, -1, None),
        'featureName': (0, -1, None),
        'sourceIndication': (0, 1, None),
        'textContent': (0, 1, None),
        'categoryOfSignalStationWarning': (1, -1, [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]),
        'communicationChannel': (0, -1, None),
        'status': (0, -1, [1, 2, 4, 5, 7, 8, 12, 14, 15, 16, 17]),
    },
    'SignalStationTraffic': {
        'fixedDateRange': (0, 1, None),
        'periodicDateRange': (0, -1, None),
        'featureName': (0, -1, None),
        'sourceIndication': (0, 1, None),
        'textContent': (0, 1, None),
        'categoryOfSignalStationTraffic': (1, -1, [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 13]),
        'communicationChannel': (0, -1, None),
        'status': (0, -1, [1, 2, 4, 5, 7, 8, 12, 14, 15, 16, 17]),
    },
    'UnderkeelClearanceAllowanceArea': {
        'fixedDateRange': (0, 1, None),
        'periodicDateRange': (0, -1, None),
        'featureName': (0, -1, None),
        'sourceIndication': (0, 1, None),
        'textContent': (0, 1, None),
        'underkeelAllowance': (0, 1, None),
        'waterLevelTrend': (0, 1, [1, 2, 3]),
    },
    'UnderkeelClearanceManagementArea': {
        'fixedDateRange': (0, 1, None),
        'periodicDateRange': (0, -1, None),
        'featureName': (0, -1, None),
        'sourceIndication': (0, 1, None),
        'textContent': (0, 1, None),
        'dynamicResource': (1, 1, [1, 2, 3, 4]),
    },
    'VesselTrafficServiceArea': {
        'fixedDateRange': (0, 1, None),
        'periodicDateRange': (0, -1, None),
        'featureName': (0, -1, None),
        'sourceIndication': (0, 1, None),
        'textContent': (0, 1, None),
        'categoryOfVesselTrafficService': (0, -1, [1, 2, 3]),
        'serviceAccessProcedure': (0, 1, None),
        'requirementsForMaintenanceOfListeningWatch': (1, 1, None),
    },
    'WaterwayArea': {
        'fixedDateRange': (0, 1, None),
        'periodicDateRange': (0, -1, None),
        'featureName': (0, -1, None),
        'sourceIndication': (0, 1, None),
        'textContent': (0, 1, None),
        'dynamicResource': (1, 1, [1, 2, 3, 4]),
        'siltationRate': (0, 1, None),
        'status': (0, -1, [1, 2, 3, 4, 5, 6, 7, 8, 9, 28]),
    },
    'DataCoverage': {
        'maximumDisplayScale': (1, 1, None),
        'minimumDisplayScale': (1, 1, None),
    },
    'QualityOfNonBathymetricData': {
        'information': (0, -1, None),
        'categoryOfTemporalVariation': (0, 1, [1, 4, 5]),
        'orientationUncertainty': (0, 1, None),
        'horizontalDistanceUncertainty': (0, 1, None),
        'horizontalPositionUncertainty': (0, 1, None),
        'sourceIndication': (0, 1, None),
        'surveyDateRange': (0, 1, None),
    },
    'TextPlacement': {
        'flipBearing': (0, 1, None),
        'scaleMinimum': (0, 1, None),
        'textJustification': (1, 1, [1, 2, 3]),
        'text': (0, 1, None),
        'textType': (0, 1, [1]),
    },
    'Applicability': {
        'fixedDateRange': (0, 1, None),
        'periodicDateRange': (0, -1, None),
        'featureName': (0, -1, None),
        'sourceIndication': (0, -1, None),
        'inBallast': (0, 1, None),
        'categoryOfCargo': (0, -1, [1, 2, 3, 4, 5, 6, 7, 8, 9]),
        'categoryOfDangerousOrHazardousCargo': (0, -1, [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]),
        'categoryOfVessel': (0, 1, [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17]),
        'categoryOfVesselRegistry': (0, 1, [1, 2]),
        'logicalConnectives': (0, 1, [1, 2]),
        'thicknessOfIceCapability': (0, 1, None),
        'vesselPerformance': (0, 1, None),
        'information': (0, -1, None),
        'vesselsMeasurements': (0, -1, None),
    },
    'Authority': {
        'fixedDateRange': (0, 1, None),
        'periodicDateRange': (0, -1, None),
        'featureName': (0, -1, None),
        'sourceIndication': (0, -1, None),
        'categoryOfAuthority': (1, 1, [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]),
        'textContent': (0, 1, None),
    },
    'ContactDetails': {
        'fixedDateRange': (0, 1, None),
        'periodicDateRange': (0, -1, None),
        'featureName': (0, -1, None),
        'sourceIndication': (0, -1, None),
        'callName': (0, 1, None),
        'callSign': (0, 1, None),
        'categoryOfCommPref': (0, 1, [1, 2, 3, 4]),
        'communicationChannel': (0, -1, None),
        'contactAddress': (0, -1, None),
        'contactInstructions': (0, 1, None),
        'frequencyPair': (0, -1, None),
        'information': (0, -1, None),
        'language': (0, 1, None),
        'mMSICode': (0, 1, None),
        'onlineResource': (0, -1, None),
        'telecommunications': (0, -1, None),
        'radiocommunications': (0, -1, None),
    },
    'NauticalInformation': {
        'fixedDateRange': (0, 1, None),
        'periodicDateRange': (0, -1, None),
        'featureName': (0, -1, None),
        'sourceIndication': (0, -1, None),
        'categoryOfAuthority': (0, 1, [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]),
        'textContent': (0, -1, None),
        'graphic': (0, -1, None),
        'rxnCode': (0, -1, None),
    },
    'NonStandardWorkingDay': {
        'fixedDateRange': (0, 1, None),
        'periodicDateRange': (0, -1, None),
        'featureName': (0, -1, None),
        'sourceIndication': (0, -1, None),
        'dateFixed': (0, -1, None),
        'dateVariable': (0, -1, None),
        'information': (0, -1, None),
    },
    'ServiceHours': {
        'fixedDateRange': (0, 1, None),
        'periodicDateRange': (0, -1, None),
        'featureName': (0, -1, None),
        'sourceIndication': (0, -1, None),
        'scheduleByDayOfWeek': (1, -1, None),
        'information': (0, -1, None),
    },
    'ShipReport': {
        'fixedDateRange': (0, 1, None),
        'periodicDateRange': (0, -1, None),
        'featureName': (0, -1, None),
        'sourceIndication': (0, -1, None),
        'categoryOfShipReport': (1, -1, [1, 2, 3, 4, 5, 6, 7, 8]),
        'imoFormatForReporting': (1, 1, None),
        'noticeTime': (1, -1, None),
        'textContent': (0, 1, None),
    },
    'Recommendations': {
        'fixedDateRange': (0, 1, None),
        'periodicDateRange': (0, -1, None),
        'featureName': (0, -1, None),
        'sourceIndication': (0, -1, None),
        'categoryOfAuthority': (0, 1, [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]),
        'textContent': (0, -1, None),
        'graphic': (0, -1, None),
        'rxnCode': (0, -1, None),
    },
    'Regulations': {
        'fixedDateRange': (0, 1, None),
        'periodicDateRange': (0, -1, None),
        'featureName': (0, -1, None),
        'sourceIndication': (0, -1, None),
        'categoryOfAuthority': (0, 1, [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]),
        'textContent': (0, -1, None),
        'graphic': (0, -1, None),
        'rxnCode': (0, -1, None),
    },
    'Restrictions': {
        'fixedDateRange': (0, 1, None),
        'periodicDateRange': (0, -1, None),
        'featureName': (0, -1, None),
        'sourceIndication': (0, -1, None),
        'categoryOfAuthority': (0, 1, [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]),
        'textContent': (0, -1, None),
        'graphic': (0, -1, None),
        'rxnCode': (0, -1, None),
    },
    'SpatialQuality': {
        'categoryOfTemporalVariation': (0, 1, [1, 4, 5]),
        'qualityOfHorizontalMeasurement': (0, 1, [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]),
        'horizontalPositionUncertainty': (0, 1, None),
    },
    'SpatialQualityPoints': {
        'categoryOfTemporalVariation': (0, 1, [1, 4, 5]),
        'qualityOfHorizontalMeasurement': (0, 1, [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]),
        'horizontalPositionUncertainty': (0, 1, None),
    },
}

# 要素类 → {角色: (lower, upper, 目标类型, 关联类, roleType)}
ASSOCS = {
    'CautionArea': {
        'permission': (0, -1, ['Applicability'], 'PermissionType', 'association'),
        'theRxN': (0, -1, ['AbstractRxN'], 'AssociatedRxN', 'association'),
        'providesInformation': (0, -1, ['NauticalInformation'], 'AdditionalInformation', 'association'),
        'positions': (0, 1, ['TextPlacement'], 'TextAssociation', 'association'),
    },
    'ConcentrationOfShippingHazardArea': {
        'permission': (0, -1, ['Applicability'], 'PermissionType', 'association'),
        'theRxN': (0, -1, ['AbstractRxN'], 'AssociatedRxN', 'association'),
        'providesInformation': (0, -1, ['NauticalInformation'], 'AdditionalInformation', 'association'),
        'positions': (0, 1, ['TextPlacement'], 'TextAssociation', 'association'),
    },
    'IspsCodeSecurityLevel': {
        'permission': (0, -1, ['Applicability'], 'PermissionType', 'association'),
        'theRxN': (0, -1, ['AbstractRxN'], 'AssociatedRxN', 'association'),
        'providesInformation': (0, -1, ['NauticalInformation'], 'AdditionalInformation', 'association'),
        'positions': (0, 1, ['TextPlacement'], 'TextAssociation', 'association'),
        'theContactDetails': (0, -1, ['ContactDetails'], 'SrvContact', 'association'),
    },
    'LocalPortServiceArea': {
        'permission': (0, -1, ['Applicability'], 'PermissionType', 'association'),
        'theRxN': (0, -1, ['AbstractRxN'], 'AssociatedRxN', 'association'),
        'providesInformation': (0, -1, ['NauticalInformation'], 'AdditionalInformation', 'association'),
        'positions': (0, 1, ['TextPlacement'], 'TextAssociation', 'association'),
        'theContactDetails': (0, -1, ['ContactDetails'], 'SrvContact', 'association'),
        'controlAuthority': (0, 1, ['Authority'], 'SrvControl', 'association'),
        'reptForTrafficServ': (0, -1, ['ShipReport'], 'TrafficServRept', 'association'),
        'consistsOf': (
            0,
            -1,
            ['RadioCallingInPoint', 'RadarRange', 'SignalStationWarning', 'SignalStationTraffic'],
            'TrafficControlServiceAggregation',
            'aggregation',
        ),
    },
    'MilitaryPracticeArea': {
        'permission': (0, -1, ['Applicability'], 'PermissionType', 'association'),
        'theRxN': (0, -1, ['AbstractRxN'], 'AssociatedRxN', 'association'),
        'providesInformation': (0, -1, ['NauticalInformation'], 'AdditionalInformation', 'association'),
        'positions': (0, 1, ['TextPlacement'], 'TextAssociation', 'association'),
        'theContactDetails': (0, -1, ['ContactDetails'], 'SrvContact', 'association'),
        'controlAuthority': (0, 1, ['Authority'], 'SrvControl', 'association'),
        'theServiceHours': (0, 1, ['ServiceHours'], 'LocationHours', 'association'),
    },
    'PilotBoardingPlace': {
        'permission': (0, -1, ['Applicability'], 'PermissionType', 'association'),
        'theRxN': (0, -1, ['AbstractRxN'], 'AssociatedRxN', 'association'),
        'providesInformation': (0, -1, ['NauticalInformation'], 'AdditionalInformation', 'association'),
        'positions': (0, 1, ['TextPlacement'], 'TextAssociation', 'association'),
        'theContactDetails': (0, -1, ['ContactDetails'], 'SrvContact', 'association'),
        'componentOf': (0, 1, ['PilotageDistrict'], 'PilotageDistrictAssociation', 'aggregation'),
        'serviceProvider': (0, -1, ['PilotService'], 'ServiceProvisionArea', 'association'),
    },
    'PilotService': {
        'permission': (0, -1, ['Applicability'], 'PermissionType', 'association'),
        'theRxN': (0, -1, ['AbstractRxN'], 'AssociatedRxN', 'association'),
        'providesInformation': (0, -1, ['NauticalInformation'], 'AdditionalInformation', 'association'),
        'positions': (0, 1, ['TextPlacement'], 'TextAssociation', 'association'),
        'theContactDetails': (0, -1, ['ContactDetails'], 'SrvContact', 'association'),
        'controlAuthority': (0, 1, ['Authority'], 'SrvControl', 'association'),
        'reptForTrafficServ': (0, -1, ['ShipReport'], 'TrafficServRept', 'association'),
        'theServiceHours': (0, 1, ['ServiceHours'], 'LocationHours', 'association'),
        'serviceArea': (0, -1, ['PilotageDistrict', 'PilotBoardingPlace'], 'ServiceProvisionArea', 'association'),
    },
    'PilotageDistrict': {
        'permission': (0, -1, ['Applicability'], 'PermissionType', 'association'),
        'theRxN': (0, -1, ['AbstractRxN'], 'AssociatedRxN', 'association'),
        'providesInformation': (0, -1, ['NauticalInformation'], 'AdditionalInformation', 'association'),
        'positions': (0, 1, ['TextPlacement'], 'TextAssociation', 'association'),
        'consistsOf': (0, -1, ['PilotBoardingPlace'], 'PilotageDistrictAssociation', 'aggregation'),
        'serviceProvider': (0, -1, ['PilotService'], 'ServiceProvisionArea', 'association'),
    },
    'PiracyRiskArea': {
        'permission': (0, -1, ['Applicability'], 'PermissionType', 'association'),
        'theRxN': (0, -1, ['AbstractRxN'], 'AssociatedRxN', 'association'),
        'providesInformation': (0, -1, ['NauticalInformation'], 'AdditionalInformation', 'association'),
        'positions': (0, 1, ['TextPlacement'], 'TextAssociation', 'association'),
        'theContactDetails': (0, -1, ['ContactDetails'], 'SrvContact', 'association'),
        'controlAuthority': (0, 1, ['Authority'], 'SrvControl', 'association'),
        'reptForTrafficServ': (0, -1, ['ShipReport'], 'TrafficServRept', 'association'),
    },
    'PlaceOfRefuge': {
        'permission': (0, -1, ['Applicability'], 'PermissionType', 'association'),
        'theRxN': (0, -1, ['AbstractRxN'], 'AssociatedRxN', 'association'),
        'providesInformation': (0, -1, ['NauticalInformation'], 'AdditionalInformation', 'association'),
        'positions': (0, 1, ['TextPlacement'], 'TextAssociation', 'association'),
        'theContactDetails': (0, -1, ['ContactDetails'], 'SrvContact', 'association'),
        'controlAuthority': (0, 1, ['Authority'], 'SrvControl', 'association'),
        'reptForTrafficServ': (0, -1, ['ShipReport'], 'TrafficServRept', 'association'),
    },
    'RadarRange': {
        'permission': (0, -1, ['Applicability'], 'PermissionType', 'association'),
        'theRxN': (0, -1, ['AbstractRxN'], 'AssociatedRxN', 'association'),
        'providesInformation': (0, -1, ['NauticalInformation'], 'AdditionalInformation', 'association'),
        'positions': (0, 1, ['TextPlacement'], 'TextAssociation', 'association'),
        'componentOf': (
            0,
            1,
            ['VesselTrafficServiceArea', 'LocalPortServiceArea', 'ShipReportingServiceArea'],
            'TrafficControlServiceAggregation',
            'association',
        ),
    },
    'RadioCallingInPoint': {
        'permission': (0, -1, ['Applicability'], 'PermissionType', 'association'),
        'theRxN': (0, -1, ['AbstractRxN'], 'AssociatedRxN', 'association'),
        'providesInformation': (0, -1, ['NauticalInformation'], 'AdditionalInformation', 'association'),
        'positions': (0, 1, ['TextPlacement'], 'TextAssociation', 'association'),
        'componentOf': (
            0,
            1,
            ['VesselTrafficServiceArea', 'LocalPortServiceArea', 'ShipReportingServiceArea'],
            'TrafficControlServiceAggregation',
            'association',
        ),
    },
    'RestrictedAreaNavigational': {
        'permission': (0, -1, ['Applicability'], 'PermissionType', 'association'),
        'theRxN': (0, -1, ['AbstractRxN'], 'AssociatedRxN', 'association'),
        'providesInformation': (0, -1, ['NauticalInformation'], 'AdditionalInformation', 'association'),
        'positions': (0, 1, ['TextPlacement'], 'TextAssociation', 'association'),
        'theContactDetails': (0, -1, ['ContactDetails'], 'SrvContact', 'association'),
        'controlAuthority': (0, 1, ['Authority'], 'SrvControl', 'association'),
    },
    'RestrictedAreaRegulatory': {
        'permission': (0, -1, ['Applicability'], 'PermissionType', 'association'),
        'theRxN': (0, -1, ['AbstractRxN'], 'AssociatedRxN', 'association'),
        'providesInformation': (0, -1, ['NauticalInformation'], 'AdditionalInformation', 'association'),
        'positions': (0, 1, ['TextPlacement'], 'TextAssociation', 'association'),
        'theContactDetails': (0, -1, ['ContactDetails'], 'SrvContact', 'association'),
        'controlAuthority': (0, 1, ['Authority'], 'SrvControl', 'association'),
    },
    'RouteingMeasure': {
        'permission': (0, -1, ['Applicability'], 'PermissionType', 'association'),
        'theRxN': (0, -1, ['AbstractRxN'], 'AssociatedRxN', 'association'),
        'providesInformation': (0, -1, ['NauticalInformation'], 'AdditionalInformation', 'association'),
        'positions': (0, 1, ['TextPlacement'], 'TextAssociation', 'association'),
    },
    'ShipReportingServiceArea': {
        'permission': (0, -1, ['Applicability'], 'PermissionType', 'association'),
        'theRxN': (0, -1, ['AbstractRxN'], 'AssociatedRxN', 'association'),
        'providesInformation': (0, -1, ['NauticalInformation'], 'AdditionalInformation', 'association'),
        'positions': (0, 1, ['TextPlacement'], 'TextAssociation', 'association'),
        'theContactDetails': (0, -1, ['ContactDetails'], 'SrvContact', 'association'),
        'controlAuthority': (0, 1, ['Authority'], 'SrvControl', 'association'),
        'reptForTrafficServ': (0, -1, ['ShipReport'], 'TrafficServRept', 'association'),
        'consistsOf': (
            0,
            -1,
            ['RadioCallingInPoint', 'RadarRange', 'SignalStationWarning', 'SignalStationTraffic'],
            'TrafficControlServiceAggregation',
            'aggregation',
        ),
    },
    'SignalStationWarning': {
        'permission': (0, -1, ['Applicability'], 'PermissionType', 'association'),
        'theRxN': (0, -1, ['AbstractRxN'], 'AssociatedRxN', 'association'),
        'providesInformation': (0, -1, ['NauticalInformation'], 'AdditionalInformation', 'association'),
        'positions': (0, 1, ['TextPlacement'], 'TextAssociation', 'association'),
        'componentOf': (
            0,
            1,
            ['VesselTrafficServiceArea', 'LocalPortServiceArea', 'ShipReportingServiceArea'],
            'TrafficControlServiceAggregation',
            'association',
        ),
    },
    'SignalStationTraffic': {
        'permission': (0, -1, ['Applicability'], 'PermissionType', 'association'),
        'theRxN': (0, -1, ['AbstractRxN'], 'AssociatedRxN', 'association'),
        'providesInformation': (0, -1, ['NauticalInformation'], 'AdditionalInformation', 'association'),
        'positions': (0, 1, ['TextPlacement'], 'TextAssociation', 'association'),
        'theContactDetails': (0, -1, ['ContactDetails'], 'SrvContact', 'association'),
        'componentOf': (
            0,
            1,
            ['VesselTrafficServiceArea', 'LocalPortServiceArea', 'ShipReportingServiceArea'],
            'TrafficControlServiceAggregation',
            'association',
        ),
    },
    'UnderkeelClearanceAllowanceArea': {
        'permission': (0, -1, ['Applicability'], 'PermissionType', 'association'),
        'theRxN': (0, -1, ['AbstractRxN'], 'AssociatedRxN', 'association'),
        'providesInformation': (0, -1, ['NauticalInformation'], 'AdditionalInformation', 'association'),
        'positions': (0, 1, ['TextPlacement'], 'TextAssociation', 'association'),
    },
    'UnderkeelClearanceManagementArea': {
        'permission': (0, -1, ['Applicability'], 'PermissionType', 'association'),
        'theRxN': (0, -1, ['AbstractRxN'], 'AssociatedRxN', 'association'),
        'providesInformation': (0, -1, ['NauticalInformation'], 'AdditionalInformation', 'association'),
        'positions': (0, 1, ['TextPlacement'], 'TextAssociation', 'association'),
        'theContactDetails': (0, -1, ['ContactDetails'], 'SrvContact', 'association'),
        'controlAuthority': (0, 1, ['Authority'], 'SrvControl', 'association'),
        'reptForTrafficServ': (0, -1, ['ShipReport'], 'TrafficServRept', 'association'),
    },
    'VesselTrafficServiceArea': {
        'permission': (0, -1, ['Applicability'], 'PermissionType', 'association'),
        'theRxN': (0, -1, ['AbstractRxN'], 'AssociatedRxN', 'association'),
        'providesInformation': (0, -1, ['NauticalInformation'], 'AdditionalInformation', 'association'),
        'positions': (0, 1, ['TextPlacement'], 'TextAssociation', 'association'),
        'theContactDetails': (0, -1, ['ContactDetails'], 'SrvContact', 'association'),
        'controlAuthority': (0, 1, ['Authority'], 'SrvControl', 'association'),
        'reptForTrafficServ': (0, -1, ['ShipReport'], 'TrafficServRept', 'association'),
        'consistsOf': (
            0,
            -1,
            ['RadioCallingInPoint', 'RadarRange', 'SignalStationWarning', 'SignalStationTraffic'],
            'TrafficControlServiceAggregation',
            'aggregation',
        ),
    },
    'WaterwayArea': {
        'permission': (0, -1, ['Applicability'], 'PermissionType', 'association'),
        'theRxN': (0, -1, ['AbstractRxN'], 'AssociatedRxN', 'association'),
        'providesInformation': (0, -1, ['NauticalInformation'], 'AdditionalInformation', 'association'),
        'positions': (0, 1, ['TextPlacement'], 'TextAssociation', 'association'),
        'theContactDetails': (0, -1, ['ContactDetails'], 'SrvContact', 'association'),
        'controlAuthority': (0, 1, ['Authority'], 'SrvControl', 'association'),
    },
    'DataCoverage': {},
    'QualityOfNonBathymetricData': {},
    'TextPlacement': {
        'identifies': (1, 1, ['FeatureType'], 'TextAssociation', 'association'),
    },
    'Applicability': {
        'providesInformation': (0, -1, ['NauticalInformation'], 'AdditionalInformation', 'association'),
        'theApplicableRxN': (0, -1, ['AbstractRxN'], 'InclusionType', 'association'),
        'theShipReport': (0, -1, ['ShipReport'], 'ReportReqmt', 'association'),
        'vslLocation': (0, -1, ['InformationType'], 'PermissionType', 'association'),
    },
    'Authority': {
        'providesInformation': (0, -1, ['NauticalInformation'], 'AdditionalInformation', 'association'),
        'theContactDetails': (0, -1, ['ContactDetails'], 'AuthorityContact', 'association'),
        'theShipReport': (0, -1, ['ShipReport'], 'ReptAuthority', 'association'),
        'theInformation': (0, -1, ['AbstractRxN'], 'RelatedOrganisation', 'association'),
        'theServiceHours': (0, -1, ['ServiceHours'], 'AuthorityHours', 'association'),
    },
    'ContactDetails': {
        'providesInformation': (0, -1, ['NauticalInformation'], 'AdditionalInformation', 'association'),
        'theAuthority': (0, -1, ['Authority'], 'AuthorityContact', 'association'),
    },
    'NauticalInformation': {
        'providesInformation': (0, -1, ['NauticalInformation'], 'AdditionalInformation', 'association'),
        'isApplicableTo': (0, -1, ['Applicability'], 'InclusionType', 'association'),
        'theOrganisation': (0, -1, ['AbstractRxN'], 'RelatedOrganisation', 'association'),
        'informationProvidedFor': (0, -1, ['InformationType'], 'AdditionalInformation', 'association'),
    },
    'NonStandardWorkingDay': {
        'providesInformation': (0, -1, ['NauticalInformation'], 'AdditionalInformation', 'association'),
    },
    'ServiceHours': {
        'providesInformation': (0, -1, ['NauticalInformation'], 'AdditionalInformation', 'association'),
        'partialWorkingDay': (0, -1, ['NonStandardWorkingDay'], 'ExceptionalWorkday', 'association'),
        'theAuthority_srvHrs': (0, -1, ['Authority'], 'AuthorityHours', 'association'),
    },
    'ShipReport': {
        'providesInformation': (0, -1, ['NauticalInformation'], 'AdditionalInformation', 'association'),
        'mustBeFiledBy': (0, -1, ['Applicability'], 'ReportReqmt', 'association'),
        'reportTo': (0, -1, ['Authority'], 'ReptAuthority', 'association'),
    },
    'Recommendations': {
        'providesInformation': (0, -1, ['NauticalInformation'], 'AdditionalInformation', 'association'),
        'isApplicableTo': (0, -1, ['Applicability'], 'InclusionType', 'association'),
        'theOrganisation': (0, -1, ['AbstractRxN'], 'RelatedOrganisation', 'association'),
    },
    'Regulations': {
        'providesInformation': (0, -1, ['NauticalInformation'], 'AdditionalInformation', 'association'),
        'isApplicableTo': (0, -1, ['Applicability'], 'InclusionType', 'association'),
        'theOrganisation': (0, -1, ['AbstractRxN'], 'RelatedOrganisation', 'association'),
    },
    'Restrictions': {
        'providesInformation': (0, -1, ['NauticalInformation'], 'AdditionalInformation', 'association'),
        'isApplicableTo': (0, -1, ['Applicability'], 'InclusionType', 'association'),
        'theOrganisation': (0, -1, ['AbstractRxN'], 'RelatedOrganisation', 'association'),
    },
    'SpatialQuality': {},
    'SpatialQualityPoints': {},
}

# 属性 → 名称 / 值类型
ATTRIBUTES = {
    'administrativeDivision': {
        'name': 'Administrative Division',
        'valueType': 'text',
    },
    'applicationProfile': {
        'name': 'Application profile',
        'valueType': 'text',
    },
    'inBallast': {
        'name': 'In ballast',
        'valueType': 'boolean',
    },
    'callName': {
        'name': 'Call Name',
        'valueType': 'text',
    },
    'callSign': {
        'name': 'Call sign',
        'valueType': 'text',
    },
    'cardinalDirection': {
        'name': 'Cardinal direction',
        'valueType': 'enumeration',
    },
    'categoryOfAuthority': {
        'name': 'Category of authority',
        'valueType': 'enumeration',
    },
    'categoryOfCargo': {
        'name': 'Category of cargo',
        'valueType': 'enumeration',
    },
    'categoryOfCommPref': {
        'name': 'Category of communication preference',
        'valueType': 'enumeration',
    },
    'categoryOfConcentrationOfShippingHazardArea': {
        'name': 'Category of concentration of shipping hazard area',
        'valueType': 'enumeration',
    },
    'categoryOfDangerousOrHazardousCargo': {
        'name': 'Category of dangerous or hazardous cargo',
        'valueType': 'enumeration',
    },
    'categoryOfMaritimeBroadcast': {
        'name': 'Category of maritime broadcast',
        'valueType': 'enumeration',
    },
    'categoryOfMilitaryPracticeArea': {
        'name': 'Category of military practice area',
        'valueType': 'enumeration',
    },
    'categoryOfNavigationLine': {
        'name': 'Category of navigation line',
        'valueType': 'enumeration',
    },
    'categoryOfPilot': {
        'name': 'Category of pilot',
        'valueType': 'enumeration',
    },
    'categoryOfPilotBoardingPlace': {
        'name': 'Category of pilot boarding place',
        'valueType': 'enumeration',
    },
    'categoryOfPreference': {
        'name': 'Category of preference',
        'valueType': 'enumeration',
    },
    'categoryOfRadioMethods': {
        'name': 'Category of radio methods',
        'valueType': 'enumeration',
    },
    'categoryOfRelationship': {
        'name': 'Category of relationship',
        'valueType': 'enumeration',
    },
    'categoryOfRestrictedArea': {
        'name': 'Category of restricted area',
        'valueType': 'enumeration',
    },
    'categoryOfRouteingMeasure': {
        'name': 'Category of routeing measure',
        'valueType': 'enumeration',
    },
    'categoryOfShipReport': {
        'name': 'Category of ship report',
        'valueType': 'enumeration',
    },
    'categoryOfSignalStationTraffic': {
        'name': 'Category of signal station, traffic',
        'valueType': 'enumeration',
    },
    'categoryOfSignalStationWarning': {
        'name': 'Category of signal station, warning',
        'valueType': 'enumeration',
    },
    'categoryOfTrafficSeparationScheme': {
        'name': 'Category of Traffic Separation Scheme',
        'valueType': 'enumeration',
    },
    'categoryOfTemporalVariation': {
        'name': 'Category of temporal variation',
        'valueType': 'enumeration',
    },
    'categoryOfText': {
        'name': 'Category of text',
        'valueType': 'enumeration',
    },
    'categoryOfVesselRegistry': {
        'name': 'Category of vessel registry',
        'valueType': 'enumeration',
    },
    'categoryOfVesselTrafficService': {
        'name': 'Category of vessel traffic service',
        'valueType': 'enumeration',
    },
    'cityName': {
        'name': 'City name',
        'valueType': 'text',
    },
    'communicationChannel': {
        'name': 'Communication channel',
        'valueType': 'text',
    },
    'comparisonOperator': {
        'name': 'Comparison Operator',
        'valueType': 'enumeration',
    },
    'condition': {
        'name': 'Condition',
        'valueType': 'enumeration',
    },
    'contactInstructions': {
        'name': 'Contact instructions',
        'valueType': 'text',
    },
    'countryName': {
        'name': 'Country Name',
        'valueType': 'text',
    },
    'dayOfWeek': {
        'name': 'Day of Week',
        'valueType': 'enumeration',
    },
    'dayOfWeekIsRange': {
        'name': 'Day of week is range',
        'valueType': 'boolean',
    },
    'dateEnd': {
        'name': 'Date end',
        'valueType': 'S100_TruncatedDate',
    },
    'dateStart': {
        'name': 'Date start',
        'valueType': 'S100_TruncatedDate',
    },
    'deliveryPoint': {
        'name': 'Delivery point',
        'valueType': 'text',
    },
    'destination': {
        'name': 'Destination',
        'valueType': 'text',
    },
    'displayName': {
        'name': 'Display name',
        'valueType': 'boolean',
    },
    'distance': {
        'name': 'Distance',
        'valueType': 'real',
    },
    'dynamicResource': {
        'name': 'Dynamic resource',
        'valueType': 'enumeration',
    },
    'fileLocator': {
        'name': 'File Locator',
        'valueType': 'text',
    },
    'fileReference': {
        'name': 'File Reference',
        'valueType': 'text',
    },
    'dateFixed': {
        'name': 'Date fixed',
        'valueType': 'S100_TruncatedDate',
    },
    'flipBearing': {
        'name': 'Flip bearing',
        'valueType': 'integer',
    },
    'frequencyShoreStationReceives': {
        'name': 'Frequency Shore Station Receives',
        'valueType': 'integer',
    },
    'frequencyShoreStationTransmits': {
        'name': 'Frequency Shore Station Transmits',
        'valueType': 'integer',
    },
    'headline': {
        'name': 'Headline',
        'valueType': 'text',
    },
    'horizontalDistanceUncertainty': {
        'name': 'Horizontal distance uncertainty',
        'valueType': 'real',
    },
    'imoFormatForReporting': {
        'name': 'IMO format for reporting',
        'valueType': 'boolean',
    },
    'ispsLevel': {
        'name': 'ISPS level',
        'valueType': 'enumeration',
    },
    'language': {
        'name': 'Language',
        'valueType': 'text',
    },
    'logicalConnectives': {
        'name': 'Logical Connectives',
        'valueType': 'enumeration',
    },
    'linkage': {
        'name': 'Linkage',
        'valueType': 'URL',
    },
    'membership': {
        'name': 'Membership',
        'valueType': 'enumeration',
    },
    'mMSICode': {
        'name': 'MMSI Code',
        'valueType': 'text',
    },
    'nationality': {
        'name': 'Nationality',
        'valueType': 'text',
    },
    'noticeTimeHours': {
        'name': 'Notice time hours',
        'valueType': 'real',
    },
    'noticeTimeText': {
        'name': 'Notice time text',
        'valueType': 'text',
    },
    'name': {
        'name': 'Name',
        'valueType': 'text',
    },
    'nameOfResource': {
        'name': 'Name of resource',
        'valueType': 'text',
    },
    'onlineResourceDescription': {
        'name': 'Online resource description',
        'valueType': 'text',
    },
    'operation': {
        'name': 'Operation',
        'valueType': 'enumeration',
    },
    'orientationUncertainty': {
        'name': 'Orientation uncertainty',
        'valueType': 'real',
    },
    'pictureCaption': {
        'name': 'Picture caption',
        'valueType': 'text',
    },
    'pictureInformation': {
        'name': 'Picture information',
        'valueType': 'text',
    },
    'pilotMovement': {
        'name': 'Pilot movement',
        'valueType': 'enumeration',
    },
    'pilotQualification': {
        'name': 'Pilot qualification',
        'valueType': 'enumeration',
    },
    'pilotRequest': {
        'name': 'Pilot request',
        'valueType': 'text',
    },
    'pilotVessel': {
        'name': 'Pilot vessel',
        'valueType': 'text',
    },
    'postalCode': {
        'name': 'Postal code',
        'valueType': 'text',
    },
    'protocol': {
        'name': 'Protocol',
        'valueType': 'text',
    },
    'protocolRequest': {
        'name': 'Protocol request',
        'valueType': 'text',
    },
    'remotePilot': {
        'name': 'Remote pilot',
        'valueType': 'boolean',
    },
    'reportedDate': {
        'name': 'Reported date',
        'valueType': 'S100_TruncatedDate',
    },
    'requirementsForMaintenanceOfListeningWatch': {
        'name': 'Requirements for maintenance of listening watch',
        'valueType': 'text',
    },
    'restriction': {
        'name': 'Restriction',
        'valueType': 'enumeration',
    },
    'scaleMinimum': {
        'name': 'Scale minimum',
        'valueType': 'integer',
    },
    'serviceAccessProcedure': {
        'name': 'Service access procedure',
        'valueType': 'text',
    },
    'signalFrequency': {
        'name': 'Signal frequency',
        'valueType': 'integer',
    },
    'siltationRate': {
        'name': 'Siltation rate',
        'valueType': 'text',
    },
    'source': {
        'name': 'Source',
        'valueType': 'text',
    },
    'sourceType': {
        'name': 'Source type',
        'valueType': 'enumeration',
    },
    'status': {
        'name': 'Status',
        'valueType': 'enumeration',
    },
    'telecommunicationIdentifier': {
        'name': 'Telecommunication identifier',
        'valueType': 'text',
    },
    'telcomCarrier': {
        'name': 'Telecommunication carrier',
        'valueType': 'text',
    },
    'text': {
        'name': 'Text',
        'valueType': 'text',
    },
    'thicknessOfIceCapability': {
        'name': 'Thickness of ice capability',
        'valueType': 'integer',
    },
    'timeOfDayEnd': {
        'name': 'Time of day end',
        'valueType': 'time',
    },
    'timeOfDayStart': {
        'name': 'Time of day start',
        'valueType': 'time',
    },
    'trafficFlow': {
        'name': 'Traffic flow',
        'valueType': 'enumeration',
    },
    'uncertaintyFixed': {
        'name': 'Uncertainty Fixed',
        'valueType': 'real',
    },
    'uncertaintyVariableFactor': {
        'name': 'Uncertainty Variable Factor',
        'valueType': 'real',
    },
    'transmissionContent': {
        'name': 'Transmission content',
        'valueType': 'text',
    },
    'underkeelAllowanceFixed': {
        'name': 'Underkeel allowance fixed',
        'valueType': 'real',
    },
    'underkeelAllowanceVariableBeamBased': {
        'name': 'Underkeel allowance variable beam based',
        'valueType': 'real',
    },
    'underkeelAllowanceVariableDraughtBased': {
        'name': 'Underkeel allowance variable draught based',
        'valueType': 'real',
    },
    'vesselsCharacteristics': {
        'name': 'Vessels characteristics',
        'valueType': 'enumeration',
    },
    'vesselsCharacteristicsUnit': {
        'name': 'Vessels characteristics unit',
        'valueType': 'enumeration',
    },
    'vesselsCharacteristicsValue': {
        'name': 'Vessels characteristics value',
        'valueType': 'real',
    },
    'vesselPerformance': {
        'name': 'Vessel performance',
        'valueType': 'text',
    },
    'qualityOfHorizontalMeasurement': {
        'name': 'Quality of horizontal measurement',
        'valueType': 'enumeration',
    },
    'maximumDisplayScale': {
        'name': 'Maximum display scale',
        'valueType': 'integer',
    },
    'minimumDisplayScale': {
        'name': 'Minimum display scale',
        'valueType': 'integer',
    },
    'orientationValue': {
        'name': 'Orientation value',
        'valueType': 'real',
    },
    'pictorialRepresentation': {
        'name': 'Pictorial representation',
        'valueType': 'text',
    },
    'sectorBearing': {
        'name': 'Sector bearing',
        'valueType': 'real',
    },
    'sourceDate': {
        'name': 'Source date',
        'valueType': 'text',
    },
    'dateVariable': {
        'name': 'Date variable',
        'valueType': 'text',
    },
    'waterLevelTrend': {
        'name': 'Water level trend',
        'valueType': 'enumeration',
    },
    'actionOrActivity': {
        'name': 'Action or activity',
        'valueType': 'S100_CodeList',
    },
    'categoryOfRxN': {
        'name': 'Category of RxN',
        'valueType': 'S100_CodeList',
    },
    'categoryOfSchedule': {
        'name': 'Category of schedule',
        'valueType': 'S100_CodeList',
    },
    'categoryOfVessel': {
        'name': 'Category of vessel',
        'valueType': 'S100_CodeList',
    },
    'onlineFunction': {
        'name': 'Online function',
        'valueType': 'S100_CodeList',
    },
    'telecommunicationService': {
        'name': 'Telecommunication service',
        'valueType': 'S100_CodeList',
    },
    'textJustification': {
        'name': 'Text justification',
        'valueType': 'enumeration',
    },
    'textType': {
        'name': 'Text type',
        'valueType': 'enumeration',
    },
    'bearingInformation': {
        'name': 'Bearing information',
        'valueType': 'complex',
    },
    'contactAddress': {
        'name': 'Contact address',
        'valueType': 'complex',
    },
    'featureName': {
        'name': 'Feature name',
        'valueType': 'complex',
    },
    'fixedDateRange': {
        'name': 'Fixed date range',
        'valueType': 'complex',
    },
    'frequencyPair': {
        'name': 'Frequency pair',
        'valueType': 'complex',
    },
    'graphic': {
        'name': 'Graphic',
        'valueType': 'complex',
    },
    'horizontalPositionUncertainty': {
        'name': 'Horizontal position uncertainty',
        'valueType': 'complex',
    },
    'information': {
        'name': 'Information',
        'valueType': 'complex',
    },
    'noticeTime': {
        'name': 'Notice time',
        'valueType': 'complex',
    },
    'onlineResource': {
        'name': 'Online resource',
        'valueType': 'complex',
    },
    'orientation': {
        'name': 'Orientation',
        'valueType': 'complex',
    },
    'scheduleByDayOfWeek': {
        'name': 'Schedule by day of week',
        'valueType': 'complex',
    },
    'periodicDateRange': {
        'name': 'Periodic date range',
        'valueType': 'complex',
    },
    'radiocommunications': {
        'name': 'Radiocommunications',
        'valueType': 'complex',
    },
    'rxnCode': {
        'name': 'RxN Code',
        'valueType': 'complex',
    },
    'sourceIndication': {
        'name': 'Source indication',
        'valueType': 'complex',
    },
    'surveyDateRange': {
        'name': 'Survey date range',
        'valueType': 'complex',
    },
    'telecommunications': {
        'name': 'Telecommunications',
        'valueType': 'complex',
    },
    'textContent': {
        'name': 'Text content',
        'valueType': 'complex',
    },
    'timeIntervalsByDayOfWeek': {
        'name': 'Time intervals by day of week',
        'valueType': 'complex',
    },
    'underkeelAllowance': {
        'name': 'Underkeel allowance',
        'valueType': 'complex',
    },
    'vesselsMeasurements': {
        'name': 'Vessels measurements',
        'valueType': 'complex',
    },
}

# 枚举属性 → {label: 官方 code}
ENUMS = {
    'cardinalDirection': {
        'N': 1,
        'NNE': 2,
        'NE': 3,
        'ENE': 4,
        'E': 5,
        'ESE': 6,
        'SE': 7,
        'SSE': 8,
        'S': 9,
        'SSW': 10,
        'SW': 11,
        'WSW': 12,
        'W': 13,
        'WNW': 14,
        'NW': 15,
        'NNW': 16,
    },
    'categoryOfAuthority': {
        'customs': 1,
        'border control': 2,
        'police': 3,
        'port': 4,
        'immigration': 5,
        'health': 6,
        'coast guard': 7,
        'agricultural': 8,
        'military': 9,
        'private company': 10,
        'maritime police': 11,
        'environmental': 12,
        'fishery': 13,
        'finance': 14,
        'maritime': 15,
    },
    'categoryOfCargo': {
        'bulk': 1,
        'container': 2,
        'general': 3,
        'liquid': 4,
        'passenger': 5,
        'livestock': 6,
        'dangerous or hazardous': 7,
        'heavy lift': 8,
        'ballast': 9,
    },
    'categoryOfCommPref': {
        'preferred calling': 1,
        'alternate calling': 2,
        'preferred working': 3,
        'alternate working': 4,
    },
    'categoryOfConcentrationOfShippingHazardArea': {
        'concentration of merchant shipping': 1,
        'concentration of recreational vessels': 2,
        'concentration of fishing vessels': 3,
        'concentration of military vessels': 4,
    },
    'categoryOfDangerousOrHazardousCargo': {
        'IMDG Code Class 1 Div. 1.1': 1,
        'IMDG Code Class 1 Div. 1.2': 2,
        'IMDG Code Class 1 Div. 1.3': 3,
        'IMDG Code Class 1 Div. 1.4': 4,
        'IMDG Code Class 1 Div. 1.5': 5,
        'IMDG Code Class 1 Div. 1.6': 6,
        'IMDG Code Class 2 Div. 2.1': 7,
        'IMDG Code Class 2 Div. 2.2': 8,
        'IMDG Code Class 2 Div. 2.3': 9,
        'IMDG Code Class 3': 10,
        'IMDG Code Class 4 Div. 4.1': 11,
        'IMDG Code Class 4 Div. 4.2': 12,
        'IMDG Code Class 4 Div. 4.3': 13,
        'IMDG Code Class 5 Div. 5.1': 14,
        'IMDG Code Class 5 Div. 5.2': 15,
        'IMDG Code Class 6 Div. 6.1': 16,
        'IMDG Code Class 6 Div. 6.2': 17,
        'IMDG Code Class 7': 18,
        'IMDG Code Class 8': 19,
        'IMDG Code Class 9': 20,
        'Harmful Substances in packaged form': 21,
    },
    'categoryOfMaritimeBroadcast': {
        'navigational warning': 1,
        'meteorological warning': 2,
        'ice report': 3,
        'SAR information': 4,
        'pirate attack warning': 5,
        'meteorological forecast': 6,
        'pilot service message': 7,
        'AIS information': 8,
        'LORAN message': 9,
        'SATNAV message': 10,
        'gale warning': 11,
        'storm warning': 12,
        'tropical revolving storm warning': 13,
        'NAVAREA warning': 14,
        'coastal warning': 15,
        'local warning': 16,
        'low water level warning/negative tidal surge': 17,
        'icing warning': 18,
        'tsunami broadcast': 19,
    },
    'categoryOfMilitaryPracticeArea': {
        'torpedo exercise area': 2,
        'submarine exercise area': 3,
        'firing danger area': 4,
        'mine-laying practice area': 5,
        'small arms firing range': 6,
    },
    'categoryOfNavigationLine': {
        'clearing line': 1,
        'transit line': 2,
        'leading line bearing a recommended track': 3,
    },
    'categoryOfPilot': {
        'pilot': 1,
        'deep sea': 2,
        'harbour': 3,
        'bar': 4,
        'river': 5,
        'channel': 6,
        'lake': 7,
    },
    'categoryOfPilotBoardingPlace': {
        'boarding by pilot-cruising vessel': 1,
        'boarding by helicopter': 2,
        'pilot comes out from shore': 3,
    },
    'categoryOfPreference': {
        'primary': 1,
        'alternate': 2,
    },
    'categoryOfRadioMethods': {
        'Low Frequency (LF) voice traffic': 1,
        'Medium Frequency (MF) voice traffic': 2,
        'High Frequency (HF) voice traffic': 3,
        'Very High Frequency (VHF) voice traffic': 4,
        'High Frequency Narrow Band Direct Printing': 5,
        'NAVTEX': 6,
        'SafetyNET': 7,
        'NBDP Telegraphy (Narrow Band Direct Printing Telegraphy)': 8,
        'facsimile': 9,
        'NAVIP': 10,
        'Low Frequency (LF) digital traffic': 11,
        'Medium Frequency (MF) digital traffic': 12,
        'High Frequency (HF) digital traffic': 13,
        'Very High Frequency (VHF) digital traffic': 14,
        'Low Frequency (LF) telegraph traffic': 15,
        'Medium Frequency (MF) telegraph traffic': 16,
        'High Frequency (HF) telegraph traffic': 17,
        'Medium Frequency (MF) Digital Selective Call traffic': 18,
        'High Frequency (HF) Digital Selective Call traffic': 19,
        'Very High Frequency (VHF) Digital Selective Call traffic': 20,
    },
    'categoryOfRelationship': {
        'prohibited': 1,
        'not recommended': 2,
        'permitted': 3,
        'recommended': 4,
        'required': 5,
        'not required': 6,
    },
    'categoryOfRestrictedArea': {
        'offshore safety zone': 1,
        'nature reserve': 4,
        'bird sanctuary': 5,
        'game reserve': 6,
        'seal sanctuary': 7,
        'degaussing range': 8,
        'military area': 9,
        'historic wreck area': 10,
        'navigational aid safety zone': 12,
        'minefield': 14,
        'waiting area': 19,
        'research area': 20,
        'fish sanctuary': 22,
        'ecological reserve': 23,
        'swinging area': 25,
        'environmentally sensitive sea area': 27,
        'particularly sensitive sea area': 28,
        'disengagement area': 29,
        'port security area': 30,
        'coral sanctuary': 31,
        'recreation area': 32,
    },
    'categoryOfRouteingMeasure': {
        'archipelagic sea lane': 1,
        'deep water route': 2,
        'fairway system': 3,
        'recommended route': 4,
        'traffic separation scheme': 5,
        'two-way route': 6,
    },
    'categoryOfShipReport': {
        'sailing plan': 1,
        'position report': 2,
        'deviation report': 3,
        'final report': 4,
        'dangerous goods report': 5,
        'harmful substances report': 6,
        'marine pollutants report': 7,
        'any other report': 8,
    },
    'categoryOfSignalStationTraffic': {
        'port control': 1,
        'port entry and departure': 2,
        'International Port Traffic': 3,
        'berthing': 4,
        'dock': 5,
        'lock': 6,
        'flood barrage': 7,
        'bridge passage': 8,
        'dredging': 9,
        'traffic control light': 10,
        'oncoming traffic indication': 13,
    },
    'categoryOfSignalStationWarning': {
        'danger': 1,
        'maritime obstruction': 2,
        'cable': 3,
        'military practice': 4,
        'distress': 5,
        'weather': 6,
        'storm': 7,
        'ice': 8,
        'time': 9,
        'tide': 10,
        'tidal stream': 11,
        'tide gauge': 12,
        'tide scale': 13,
        'diving': 14,
        'water level gauge': 15,
        'vertical clearance indication': 16,
        'high water mark': 17,
        'depth indication': 18,
    },
    'categoryOfTrafficSeparationScheme': {
        'IMO - Adopted': 1,
        'not IMO - adopted': 2,
    },
    'categoryOfTemporalVariation': {
        'Extreme Event': 1,
        'Likely to Change': 4,
        'Unlikely to Change': 5,
    },
    'categoryOfText': {
        'abstract or summary': 1,
        'extract': 2,
        'full text': 3,
    },
    'categoryOfVesselRegistry': {
        'domestic': 1,
        'foreign': 2,
    },
    'categoryOfVesselTrafficService': {
        'Information Service': 1,
        'Traffic Organisation Service': 2,
        'Navigational Assistance Service': 3,
    },
    'comparisonOperator': {
        'greater than': 1,
        'greater than or equal to': 2,
        'less than': 3,
        'less than or equal to': 4,
        'equal to': 5,
        'not equal to': 6,
    },
    'condition': {
        'under construction': 1,
        'under reclamation': 3,
        'planned construction': 5,
    },
    'dayOfWeek': {
        'Sunday': 1,
        'Monday': 2,
        'Tuesday': 3,
        'Wednesday': 4,
        'Thursday': 5,
        'Friday': 6,
        'Saturday': 7,
    },
    'dynamicResource': {
        'static': 1,
        'mandatory external dynamic': 2,
        'optional external dynamic': 3,
        'onboard dynamic': 4,
    },
    'ispsLevel': {
        'ISPS Level 1': 1,
        'ISPS Level 2': 2,
        'ISPS Level 3': 3,
    },
    'logicalConnectives': {
        'logical conjunction': 1,
        'logical disjunction': 2,
    },
    'membership': {
        'included': 1,
        'excluded': 2,
    },
    'operation': {
        'largest value': 1,
        'smallest value': 2,
    },
    'pilotMovement': {
        'embarkation': 1,
        'disembarkation': 2,
        'pilot change': 3,
    },
    'pilotQualification': {
        'government pilot': 1,
        'pilot approved by government': 2,
        'state pilot': 3,
        'federal pilot': 4,
        'company pilot': 5,
        'local pilot': 6,
        'citizen with sufficient local knowledge': 7,
        'citizen with doubtful local knowledge': 8,
    },
    'restriction': {
        'anchoring prohibited': 1,
        'anchoring restricted': 2,
        'fishing prohibited': 3,
        'fishing restricted': 4,
        'trawling prohibited': 5,
        'trawling restricted': 6,
        'entry prohibited': 7,
        'entry restricted': 8,
        'dredging prohibited': 9,
        'dredging restricted': 10,
        'diving prohibited': 11,
        'diving restricted': 12,
        'no wake': 13,
        'area to be avoided': 14,
        'construction prohibited': 15,
        'discharging prohibited': 16,
        'discharging restricted': 17,
        'industrial or mineral exploration/development prohibited': 18,
        'industrial or mineral exploration/development restricted': 19,
        'drilling prohibited': 20,
        'drilling restricted': 21,
        'removal of historical artifacts prohibited': 22,
        'cargo transhipment (lightering) prohibited': 23,
        'dragging prohibited': 24,
        'stopping prohibited': 25,
        'landing prohibited': 26,
        'speed restricted': 27,
        'overtaking prohibited': 28,
        'overtaking of convoys by convoys prohibited': 29,
        'passing or overtaking prohibited': 30,
        'berthing prohibited': 31,
        'berthing restricted': 32,
        'making fast prohibited': 33,
        'making fast restricted': 34,
        'turning prohibited': 35,
        'restricted fairway depth': 36,
        'restricted fairway width': 37,
        'swimming prohibited': 39,
    },
    'sourceType': {
        'law or regulation': 1,
        'official publication': 2,
        'mariner report, confirmed': 7,
        'mariner report, not confirmed': 8,
        'industry publications and reports': 9,
        'remotely sensed images': 10,
        'photographs': 11,
        'products issued by HO services': 12,
        'news media': 13,
        'traffic data': 14,
    },
    'status': {
        'permanent': 1,
        'occasional': 2,
        'recommended': 3,
        'not in use': 4,
        'periodic/intermittent': 5,
        'reserved': 6,
        'temporary': 7,
        'private': 8,
        'mandatory': 9,
        'illuminated': 12,
        'public': 14,
        'synchronized': 15,
        'watched': 16,
        'un-watched': 17,
        'existence doubtful': 18,
        'buoyed': 28,
    },
    'trafficFlow': {
        'inbound': 1,
        'outbound': 2,
        'one-way': 3,
        'two-way': 4,
    },
    'vesselsCharacteristics': {
        'length overall': 1,
        'length at waterline': 2,
        'breadth': 3,
        'draught': 4,
        'height': 5,
        'displacement tonnage': 6,
        'displacement tonnage, light': 7,
        'displacement tonnage, loaded': 8,
        'deadweight tonnage': 9,
        'gross tonnage': 10,
        'net tonnage': 11,
        'Panama Canal/Universal Measurement System net tonnage': 12,
        'Suez Canal net tonnage': 13,
        'Suez Canal gross tonnage': 14,
    },
    'vesselsCharacteristicsUnit': {
        'metre': 1,
        'foot': 2,
        'metric ton': 3,
        'ton': 4,
        'short ton': 5,
        'gross ton': 6,
        'net ton': 7,
        'Panama Canal/Universal Measurement System net tonnage': 8,
        'Suez Canal Net Tonnage': 9,
        'none': 10,
        'cubic metres': 11,
        'Suez Canal Gross Tonnage': 12,
    },
    'qualityOfHorizontalMeasurement': {
        'surveyed': 1,
        'unsurveyed': 2,
        'inadequately surveyed': 3,
        'approximate': 4,
        'position doubtful': 5,
        'unreliable': 6,
        'reported (not surveyed)': 7,
        'reported (not confirmed)': 8,
        'estimated': 9,
        'precisely known': 10,
        'calculated': 11,
    },
    'waterLevelTrend': {
        'decreasing': 1,
        'increasing': 2,
        'steady': 3,
    },
    'actionOrActivity': {
        'navigating with a pilot': 1,
        'entering port': 2,
        'leaving port': 3,
        'berthing': 4,
        'slipping': 5,
        'anchoring': 6,
        'weighing anchor': 7,
        'transiting': 8,
        'overtaking': 9,
        'reporting': 10,
        'working cargo': 11,
        'landing': 12,
        'diving': 13,
        'fishing': 14,
        'discharging overboard': 15,
        'passing': 16,
    },
    'categoryOfRxN': {
        'navigation': 1,
        'communication': 2,
        'environmental protection': 3,
        'wildlife protection': 4,
        'security': 5,
        'customs': 6,
        'cargo operation': 7,
        'refuge': 8,
        'health': 9,
        'natural resources or exploitation': 10,
        'port': 11,
        'finance': 12,
        'agriculture': 13,
    },
    'categoryOfSchedule': {
        'normal operation': 1,
        'closure': 2,
        'unmanned operation': 3,
    },
    'categoryOfVessel': {
        'general cargo vessel': 1,
        'container carrier': 2,
        'tanker': 3,
        'bulk carrier': 4,
        'passenger vessel': 5,
        'roll-on roll-off': 6,
        'refrigerated cargo vessel': 7,
        'fishing vessel': 8,
        'service': 9,
        'warship': 10,
        'towed or pushed composite unit': 11,
        'tug and tow': 12,
        'light recreational': 13,
        'semi-submersible offshore installation': 14,
        'jack-up exploration or project installation': 15,
        'livestock carrier': 16,
        'sport fishing': 17,
    },
    'onlineFunction': {
        'download': 1,
        'information': 2,
        'offline access': 3,
        'order': 4,
        'search': 5,
        'complete metadata': 6,
        'browse graphic': 7,
        'upload': 8,
        'email service': 9,
        'browsing': 10,
        'file access': 11,
    },
    'telecommunicationService': {
        'voice': 1,
        'facsimile': 2,
        'SMS': 3,
        'data': 4,
        'streamedData': 5,
        'telex': 6,
        'telegraph': 7,
        'email': 8,
    },
    'textJustification': {
        'left': 1,
        'centred': 2,
        'right': 3,
    },
    'textType': {
        'feature name': 1,
    },
}

# 复合属性 → [(子属性, lower, upper, 允许枚举子集)]
COMPLEX = {
    'bearingInformation': [
        ('cardinalDirection', 0, 1, [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]),
        ('distance', 0, 1, None),
        ('sectorBearing', 0, 2, None),
        ('information', 0, -1, None),
        ('orientation', 0, 1, None),
    ],
    'contactAddress': [
        ('deliveryPoint', 0, -1, None),
        ('cityName', 0, 1, None),
        ('administrativeDivision', 0, 1, None),
        ('countryName', 0, 1, None),
        ('postalCode', 0, 1, None),
    ],
    'featureName': [('displayName', 0, 1, None), ('language', 0, 1, None), ('name', 1, 1, None)],
    'fixedDateRange': [('dateEnd', 0, 1, None), ('dateStart', 0, 1, None)],
    'frequencyPair': [
        ('frequencyShoreStationTransmits', 0, -1, None),
        ('frequencyShoreStationReceives', 0, -1, None),
        ('contactInstructions', 0, -1, None),
    ],
    'graphic': [
        ('pictorialRepresentation', 1, -1, None),
        ('pictureCaption', 0, 1, None),
        ('sourceDate', 0, 1, None),
        ('pictureInformation', 0, 1, None),
        ('bearingInformation', 0, 1, None),
    ],
    'horizontalPositionUncertainty': [('uncertaintyFixed', 1, 1, None)],
    'information': [
        ('fileLocator', 0, 1, None),
        ('fileReference', 0, 1, None),
        ('headline', 0, 1, None),
        ('language', 0, 1, None),
        ('text', 0, 1, None),
    ],
    'noticeTime': [('noticeTimeHours', 0, -1, None), ('noticeTimeText', 0, 1, None), ('operation', 0, 1, [1, 2])],
    'onlineResource': [
        ('linkage', 1, 1, None),
        ('protocol', 0, 1, None),
        ('applicationProfile', 0, 1, None),
        ('nameOfResource', 0, 1, None),
        ('onlineResourceDescription', 0, 1, None),
        ('onlineFunction', 0, 1, [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]),
        ('protocolRequest', 0, 1, None),
    ],
    'orientation': [('orientationUncertainty', 0, 1, None), ('orientationValue', 1, 1, None)],
    'scheduleByDayOfWeek': [('categoryOfSchedule', 0, 1, [1, 2, 3]), ('timeIntervalsByDayOfWeek', 1, -1, None)],
    'periodicDateRange': [('dateEnd', 1, 1, None), ('dateStart', 1, 1, None)],
    'radiocommunications': [
        ('categoryOfCommPref', 0, 1, [1, 2, 3, 4]),
        (
            'categoryOfMaritimeBroadcast',
            0,
            -1,
            [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        ),
        (
            'categoryOfRadioMethods',
            0,
            -1,
            [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
        ),
        ('communicationChannel', 0, -1, None),
        ('contactInstructions', 0, 1, None),
        ('frequencyPair', 0, -1, None),
        ('signalFrequency', 0, -1, None),
        ('transmissionContent', 0, 1, None),
        ('timeIntervalsByDayOfWeek', 0, -1, None),
    ],
    'rxnCode': [
        ('categoryOfRxN', 0, 1, [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]),
        ('actionOrActivity', 0, 1, [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]),
        ('headline', 0, 1, None),
    ],
    'sourceIndication': [
        ('categoryOfAuthority', 0, 1, [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]),
        ('countryName', 0, 1, None),
        ('reportedDate', 0, 1, None),
        ('source', 0, 1, None),
        ('sourceType', 0, 1, [1, 2, 7, 8, 9, 10, 11, 12, 13, 14]),
        ('featureName', 0, -1, None),
    ],
    'surveyDateRange': [('dateEnd', 1, 1, None), ('dateStart', 0, 1, None)],
    'telecommunications': [
        ('categoryOfCommPref', 0, 1, [1, 2, 3, 4]),
        ('telecommunicationIdentifier', 1, 1, None),
        ('telcomCarrier', 0, 1, None),
        ('contactInstructions', 0, 1, None),
        ('telecommunicationService', 0, -1, [1, 2, 3, 4, 5, 6, 7, 8]),
        ('scheduleByDayOfWeek', 0, 1, None),
    ],
    'textContent': [
        ('categoryOfText', 0, 1, [1, 2, 3]),
        ('information', 0, -1, None),
        ('onlineResource', 0, 1, None),
        ('sourceIndication', 0, 1, None),
    ],
    'timeIntervalsByDayOfWeek': [
        ('dayOfWeek', 0, 7, [1, 2, 3, 4, 5, 6, 7]),
        ('dayOfWeekIsRange', 0, 1, None),
        ('timeOfDayStart', 0, -1, None),
        ('timeOfDayEnd', 0, -1, None),
    ],
    'underkeelAllowance': [
        ('underkeelAllowanceFixed', 0, 1, None),
        ('underkeelAllowanceVariableBeamBased', 0, 1, None),
        ('underkeelAllowanceVariableDraughtBased', 0, 1, None),
        ('operation', 0, 1, [1, 2]),
    ],
    'vesselsMeasurements': [
        ('comparisonOperator', 1, 1, [1, 2, 3, 4, 5, 6]),
        ('vesselsCharacteristics', 1, 1, [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]),
        ('vesselsCharacteristicsValue', 1, 1, None),
        ('vesselsCharacteristicsUnit', 1, 1, [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]),
    ],
}

# 关联角色 → 名称 / 定义
ROLES = {
    'componentOf': {
        'name': 'Component of',
        'definition': 'A pointer to the aggregate in a whole-part relationship.',
    },
    'consistsOf': {
        'name': 'Consists of',
        'definition': 'A pointer to a part in a whole-part relationship',
    },
    'theApplicableRxN': {
        'name': 'The applicable RxN',
        'definition': 'The applicable regulation, restriction, recommendation or nautical information',
    },
    'appliesInLocation': {
        'name': 'Applies in location',
        'definition': 'The location in which the information item applies',
    },
    'theAuthority': {
        'name': 'Authority (reference)',
        'definition': 'A pointer to an Authority object',
    },
    'theAuthority_srvHrs': {
        'name': 'Authority service hours',
        'definition': 'The authority for which service hours are given',
    },
    'theContactDetails': {
        'name': 'Contact details (reference)',
        'definition': 'A pointer to an Contact Details object',
    },
    'controlAuthority': {
        'name': 'Control authority',
        'definition': 'The controlling organization or authority for a geographically located service',
    },
    'controlledService': {
        'name': 'Controlled service',
        'definition': 'The service controlled by an organisation or authority',
    },
    'definedFor': {
        'name': 'Defined for',
        'definition': 'A pointer to a specific spatial type(s).',
    },
    'defines': {
        'name': 'Defines',
        'definition': 'A pointer to an information type providing spatial quality information.',
    },
    'identifies': {
        'name': 'Identifies',
        'definition': 'A pointer to a specific feature(s).',
    },
    'informationProvidedFor': {
        'name': 'Information provided for',
        'definition': 'A pointer to a specific feature(s) for which further information is required.',
    },
    'isApplicableTo': {
        'name': 'Is applicable to',
        'definition': 'The object or class of objects to which the regulation, restriction, recommendation, or nautical information applies',
    },
    'location_srvHrs': {
        'name': 'Location service hours',
        'definition': 'The location for which service hours are given',
    },
    'theInformation': {
        'name': 'The information',
        'definition': 'Information related to an organisation',
    },
    'theOrganisation': {
        'name': 'The organisation',
        'definition': 'The organisation to which information relates',
    },
    'partialWorkingDay': {
        'name': 'Partial working day',
        'definition': 'The work hours for a non-standard workday',
    },
    'permission': {
        'name': 'Permission',
        'definition': 'The permissions for a location',
    },
    'mustBeFiledBy': {
        'name': 'Must be filed by',
        'definition': 'The class (generally, qualifying vessels) which must file the report',
    },
    'positions': {
        'name': 'Positions',
        'definition': 'A pointer to a specific cartographically positioned location for text.',
    },
    'providesInformation': {
        'name': 'Provides information',
        'definition': 'A pointer to an object that provides more information about the referencing feature or information type.',
    },
    'reptForLocation': {
        'name': 'Report for location',
        'definition': 'The feature pertaining to a report',
    },
    'reportTo': {
        'name': 'Report to',
        'definition': 'The organisation or place to which a report is sent.',
    },
    'theRxN': {
        'name': 'The RxN',
        'definition': 'The regulation, restriction, recommendation, or nautical information',
    },
    'theServiceHours': {
        'name': 'Service Hours (reference)',
        'definition': 'Service hours for an authority ore service provider',
    },
    'theServiceHours_nsdy': {
        'name': 'The service hours for a non-standard workday',
        'definition': 'The usual service hours to which an exception applies',
    },
    'servicePlace': {
        'name': 'Service place',
        'definition': 'Pointer to service or facility',
    },
    'serviceArea': {
        'name': 'Service area',
        'definition': 'The area served by a service provider.',
    },
    'serviceProvider': {
        'name': 'Service provider',
        'definition': 'Pointer to a feature from where a provider supplies a service.',
    },
    'theShipReport': {
        'name': 'The ship report',
        'definition': 'The report to be filed by a vessel',
    },
    'reptForTrafficServ': {
        'name': 'Traffic service report',
        'definition': 'The report for a traffic service',
    },
    'vslLocation': {
        'name': 'Vessel location',
        'definition': 'The location to which the permission statement applies',
    },
}

# 关联类 → 名称 / 两端角色 / 类型
ASSOC_CLASSES = {
    'AdditionalInformation': {
        'name': 'Additional information',
        'roles': ['providesInformation', 'informationProvidedFor'],
        'kind': 'information',
    },
    'AuthorityContact': {
        'name': 'Authority contact',
        'roles': ['theAuthority', 'theContactDetails'],
        'kind': 'information',
    },
    'AuthorityHours': {
        'name': 'Authority hours',
        'roles': ['theAuthority_srvHrs', 'theServiceHours'],
        'kind': 'information',
    },
    'AssociatedRxN': {
        'name': 'Associated RxN',
        'roles': ['appliesInLocation', 'theRxN'],
        'kind': 'information',
    },
    'ExceptionalWorkday': {
        'name': 'Exceptional workday',
        'roles': ['theServiceHours_nsdy', 'partialWorkingDay'],
        'kind': 'information',
    },
    'InclusionType': {
        'name': 'Inclusion type',
        'roles': ['theApplicableRxN', 'isApplicableTo'],
        'kind': 'information',
    },
    'PermissionType': {
        'name': 'Permission type',
        'roles': ['vslLocation', 'permission'],
        'kind': 'information',
    },
    'RelatedOrganisation': {
        'name': 'Related organisation',
        'roles': ['theInformation', 'theOrganisation'],
        'kind': 'information',
    },
    'ReptAuthority': {
        'name': 'Reporting authority',
        'roles': ['reportTo', 'theShipReport'],
        'kind': 'information',
    },
    'ReportReqmt': {
        'name': 'Reporting requirement',
        'roles': ['theShipReport', 'mustBeFiledBy'],
        'kind': 'information',
    },
    'SrvContact': {
        'name': 'Service contact',
        'roles': ['servicePlace', 'theContactDetails'],
        'kind': 'information',
    },
    'SrvControl': {
        'name': 'Service control',
        'roles': ['controlledService', 'controlAuthority'],
        'kind': 'information',
    },
    'SpatialAssociation': {
        'name': 'Spatial Association',
        'roles': ['definedFor', 'defines'],
        'kind': 'information',
    },
    'LocationHours': {
        'name': 'Location hours',
        'roles': ['location_srvHrs', 'theServiceHours'],
        'kind': 'information',
    },
    'TrafficServRept': {
        'name': 'Traffic service report',
        'roles': ['reptForLocation', 'reptForTrafficServ'],
        'kind': 'information',
    },
    'ServiceProvisionArea': {
        'name': 'Service provision area',
        'roles': ['serviceProvider', 'serviceArea'],
        'kind': 'feature',
    },
    'PilotageDistrictAssociation': {
        'name': 'Pilotage district association',
        'roles': ['componentOf', 'consistsOf'],
        'kind': 'feature',
    },
    'TextAssociation': {
        'name': 'Text association',
        'roles': ['identifies', 'positions'],
        'kind': 'feature',
    },
    'TrafficControlServiceAggregation': {
        'name': 'Traffic control service aggregation',
        'roles': ['componentOf', 'consistsOf'],
        'kind': 'feature',
    },
}


# ---------------------------------------------------------------------------
# 查询辅助
# ---------------------------------------------------------------------------

def binding(feature_type, attr):
    """(lower, upper, 允许枚举子集)；该要素类不允许此属性时返回 None。"""
    return BINDINGS.get(feature_type, {}).get(attr)


def assoc(feature_type, role):
    """(lower, upper, [目标类型…], 关联类, roleType)；不允许时返回 None。"""
    return ASSOCS.get(feature_type, {}).get(role)


def allowed_attributes(feature_type):
    return list(BINDINGS.get(feature_type, {}))


def allowed_roles(feature_type):
    return list(ASSOCS.get(feature_type, {}))


def required_attributes(feature_type):
    """要素目录规定 lower>=1 的属性。"""
    return [a for a, (lo, _, _) in BINDINGS.get(feature_type, {}).items() if lo >= 1]


def is_repeatable(feature_type, attr):
    b = binding(feature_type, attr)
    return bool(b) and (b[1] == -1 or b[1] > 1)


def max_occurs(attr):
    """该属性在所有绑定与复合属性里的最宽松上限（-1 = 不限）。"""
    best = 1
    for binds in BINDINGS.values():
        if attr in binds:
            up = binds[attr][1]
            if up == -1:
                return -1
            best = max(best, up)
    for subs in COMPLEX.values():
        for name, _lo, up, _pv in subs:
            if name == attr:
                if up == -1:
                    return -1
                best = max(best, up)
    return best


def sub_attributes(complex_attr):
    return [s[0] for s in COMPLEX.get(complex_attr, [])]


def permitted_labels(feature_type, attr):
    """该要素类在此属性上允许的枚举 label（要素目录可能只允许全集的子集）。"""
    table = ENUMS.get(attr)
    if not table:
        return None
    b = binding(feature_type, attr)
    if not b or b[2] is None:
        return list(table)
    allow = set(b[2])
    return [label for label, code in table.items() if code in allow]
